version: '3.1'

services:
  locadorapassatempo-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locadorapassatempo
    ports:
      - 3306:3306
